# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6c55f576d400a52ca95031045124bfff5ee4a3fbc8c06e9eb47506dbfb8c6ffa2143c112dfa59cd44e129ec3a566c3f3126de366dc493b4feac80895b3422d5

test:
  secret_key_base: 6471b2ce92911592bd97ed8ae7e542eaf165e8fa8c269a75d68bdde52f17a895a5c56c6cfb2dc6b76c3944f8c001dc4929a5e223969d69f33bb824dbb2d99a09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
